[paths]
cache_dir = ".tzp-cache"
config_dir = ".tzp-config"

[cache]
extension = ".bin"
en_hash_filename = "en.hashes.bin"

[adapters]
parser = "lua_v1"
ui = "pyside6"
cache = "binary_v1"

[formats]
translation_ext = ".txt"
comment_prefix = "--"
